## Reference: https://github.com/helm/chart-releaser
index-path: "./index.yaml"
# Set to true for GPG signing
sign: true
# UID of the GPG key to use
key: Argo Helm maintainers
keyring: ~/secring.gpg
passphrase-file: ~/passphrase.txt
