## Reference: https://github.com/helm/chart-releaser
index-path: "./index.yaml"
# Set to true for GPG signing
sign: true
# UID of the GPG key to use
key: Argo Helm maintainers
# keyring:          # Set via env variable CR_KEYRING
# passphrase-file:  # Set via env variable CR_PASSPHRASE_FILE
